name: poc_flutter_mobx
description: Quick PoC to compare some mobx implementations in Flutter, using PokéAPI.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  get_it: ^7.2.0
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.4
  build_runner: ^2.1.7

flutter:
  uses-material-design: true